[phases.build]
dependsOn = ['install']
cmds = ['npm run build',"echo \"<<<<<<<<<<<<< CHANGING THE PHP INI >>>>>>>>>>>>>>\"",
    "PHP_INI_PATH=$(php -i | grep '/php.ini' | awk '{print $6}') && echo -e '\nupload_max_filesize = 100M\npost_max_size = 100M' >> $PHP_INI_PATH",]


[phases.install]
dependsOn = ['setup']
cmds = [
'mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx',
'composer install --ignore-platform-reqs',
'npm ci',
]

[phases.setup]
nixPkgs = [
'(php82.withExtensions (pe: pe.enabled ++ [ pe.all.imagick ]))',
'nginx',
'libmysqlclient',
'php82Packages.composer',
'php82Extensions.imagick',
'nodejs_18',
'npm-9_x',
]
