[variables]
    UPLOAD_MAX_FILESIZE = '100M'
    POST_MAX_SIZE = '100M'
    MEMORY_LIMIT = '2048M'

[phases.build]
dependsOn = ['install']
cmds = [
    'npm run build',
]

[phases.install]
dependsOn = ['setup']
cmds = [
'mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx',
'composer install --ignore-platform-reqs',
'npm ci',
]

[phases.setup]
cmds = ['PHP_INI_PATH=$(php --ini | grep "Additional .ini files parsed:" | cut -d: -f2 | tr -d " "); echo "PHP_INI_PATH is $PHP_INI_PATH"; echo "memory_limit=2048M" >> $PHP_INI_PATH; echo "upload_max_filesize=100M" >> $PHP_INI_PATH; echo "post_max_size=100M" >> $PHP_INI_PATH; echo "Content of php.ini below:"; cat "$PHP_INI_PATH"']
nixPkgs = [
'(php82.withExtensions (pe: pe.enabled ++ [ pe.all.imagick ]))',
'nginx',
'libmysqlclient',
'php82Packages.composer',
'php82Extensions.imagick',
'nodejs_18',
'npm-9_x',
]
